[databases]
* = host=postgres port=5432 dbname=pg-bouncer

[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid

listen_addr = 0.0.0.0
listen_port = 6432

auth_type = trust
auth_file = /bitnami/pgbouncer/conf/userlist.txt

pool_mode = transaction

max_client_conn = 100
default_pool_size = 50
reserve_pool_size = 10
server_reset_query = DISCARD ALL

# Timeouts in seconds
server_idle_timeout = 600
server_lifetime = 3600
server_connect_timeout = 15
server_login_retry = 15
query_timeout = 0
query_wait_timeout = 120
client_idle_timeout = 0
idle_transaction_timeout = 0

# Log settings
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1
verbose = 0

# Additional settings
application_name_add_host = 1
ignore_startup_parameters = extra_float_digits