name: pgbouncer-csf

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgbouncer-csf_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgb1:
    image: bitnami/pgbouncer:1
    container_name: pgb1
    ports:
      - "6432:6432"
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRESQL_DATABASE=postgres
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_DEFAULT_POOL_SIZE=70
      - PGBOUNCER_MAX_CLIENT_CONN=4000
      - PGBOUNCER_STATS_PERIOD=60
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/6432' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgb2:
    image: bitnami/pgbouncer:1
    container_name: pgb2
    ports:
      - "6433:6432"
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRESQL_DATABASE=postgres
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_DEFAULT_POOL_SIZE=70
      - PGBOUNCER_MAX_CLIENT_CONN=4000
      - PGBOUNCER_STATS_PERIOD=60
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/6432' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgb3:
    image: bitnami/pgbouncer:1
    container_name: pgb3
    ports:
      - "6434:6432"
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRESQL_DATABASE=postgres
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_DEFAULT_POOL_SIZE=70
      - PGBOUNCER_MAX_CLIENT_CONN=4000
      - PGBOUNCER_STATS_PERIOD=60
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/6432' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgbouncer-csf_postgres_data:
